pipeline {
  agent any

  stages {
    stage("Build the Application") {
      steps {
        echo "This is build stage"
        sh "mvn clean build"
      }
    }

    stage("Packaging the Application") {
      steps {
        echo "This is packaging stage"
        sh "mvn clean package"
      }
    }
  }
}