pipeline {
  agent all

  stages {
    stage("Validate Application") {
      steps {
        echo "This is build stage"
        sh "mvn validate"
      }
    }

    stage("Compile the Application") {
      steps {
        echo "This is packaging stage"
        sh "mvn clean package"
      }
    }
  }
}