pipeline {
  agent any

  stages {
    stage("Validate Application") {
      steps {
        echo "This is build stage"
        sh "mvn validate"
      }
    }

    stage("Package the Application") {
      steps {
        echo "This is packaging stage"
        sh "mvn clean package"
      }
    }

    stage("Install the Application") {
      steps {
        echo "This is install stage"
        sh "mvn install -Dmaven.test.skip=true"
      }
    }

    stage("Deploy the Application") {
      steps {
        echo "This is deploy stage"
        sh "mvn deploy -B -DskipTests"
      }
    }
  }
}